name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: 'https://dev-wesco.crm.dynamics.com/'
        app-id: '59ed2084-023c-47a9-95bf-c2b8c3088864'
        tenant-id: '381d31b0-f4b9-4f22-a0dd-92488db3eb82'
        client-secret: '0lu.e9bduH38rDuNCghaU-6v_yh_8U7ueO'

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://dev-wesco.crm.dynamics.com/'
        app-id: '59ed2084-023c-47a9-95bf-c2b8c3088864'
        tenant-id: '381d31b0-f4b9-4f22-a0dd-92488db3eb82'
        client-secret: '0lu.e9bduH38rDuNCghaU-6v_yh_8U7ueO'
        solution-name: WESCO
        solution-output-file: out/exported/WESCO.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/WESCO.zip
        solution-folder: out/solutions/WESCO
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/solutions/WESCO
        solution-target-folder: solutions/WESCO
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
